// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tqzokhfpzruyirmktddn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxem9raGZwenJ1eWlybWt0ZGRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMjg2MjYsImV4cCI6MjA1OTYwNDYyNn0.VZhChhlCBFQsB1_M6F0O2utECez95nlGPlDsBb0IgIk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);